language: go

go:
  - 1.3.3
  - 1.7.1

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
#    - GIMME_OS=windows GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=arm GOARM=6


install:
    - go get -d -v ./rename
    - go get -d -v ./mame-history
    - go get -d -v .

script:
    - go build -tags noasm -o rename-bin -v ./rename
    - go build -tags noasm -o mame-history-bin -v ./mame-history
    - go build -tags noasm -v .
    - ./scripts/run-tests.sh
